### ISSUE TITLE
doesnt seem to work, i dont understand why

### ISSUE THREAD

**Issue by kumavis** [hidao80/Share-with-ShareGPT#1] opened 2023-04-14 18:19 UTC
![image](https://user-images.githubusercontent.com/1474978/232125359-92fadfe1-3f89-44bf-ac9c-28a5fa9ce413.png)

permissions look correct 
![image](https://user-images.githubusercontent.com/1474978/232125508-7a5bd5ac-313f-46ec-be7c-d9813bc59035.png)

**Comment by guysoft** [comment] 2023-05-10 20:54
Same issue here.

**Comment by hidao80** [comment] 2023-05-20 03:51
@kumavis  @guysoft 
Thank you for the information. 
I have released version v0.4, which addresses the URL and DOM tree changes associated with the upgrade of ChatGPT. If you would like, please feel free to use this new version.

**Comment by guysoft** [comment] 2023-05-21 17:22
I can confirm it works now. AFAIK this issue can be closed :)

**Comment by guysoft** [comment] 2023-05-22 08:52
Reopened because it does not work?

**Comment by hidao80** [comment] 2023-05-22 11:52
@guysoft 
I reopened the issue because I thought it might be better to have kumavis,
who created the issue, either report that it is working fine or close it themselves,
just to be on the safe side.

**Comment by guysoft** [comment] 2023-05-22 12:30
Cool also best to mention @kumavis just in case :)

**Comment by hidao80** [comment] 2023-05-31 23:33
It has been a week since the issue was resolved, but the person who opened the issue has not closed it,
so I will close it with the authority of the repository owner.

**Closed as completed by hidao80** 2023-05-31 23:33 UTC
